fn main() {
    // With `gui` on, tauri-build does everything: ACL/permission codegen, the
    // mobile project glue, and the `desktop` / `mobile` cfg aliases.
    #[cfg(feature = "gui")]
    tauri_build::build();

    // With `gui` off there is no `tauri` dependency, so tauri_build::build()
    // panics on the `cargo:dev` instruction that tauri's own build script would
    // have emitted. Nothing it generates is needed for the headless binaries —
    // except the two cfg aliases, which src/lib.rs gates modules on. Emit them
    // here with the same rule tauri-build uses (mobile == android | ios).
    #[cfg(not(feature = "gui"))]
    {
        println!("cargo:rustc-check-cfg=cfg(desktop)");
        println!("cargo:rustc-check-cfg=cfg(mobile)");
        let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
        if target_os == "android" || target_os == "ios" {
            println!("cargo:rustc-cfg=mobile");
        } else {
            println!("cargo:rustc-cfg=desktop");
        }
    }

    // `embed-ui` (board #323): the web UI's dist/ becomes a sorted
    // (path, include_bytes!) table the gateway serves; nothing is read from
    // disk at run time. Any change under dist/ rebuilds.
    if std::env::var_os("CARGO_FEATURE_EMBED_UI").is_some() {
        embed_ui();
    }
}

fn embed_ui() {
    let manifest = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let dist = manifest.parent().unwrap().join("dist");
    println!("cargo:rerun-if-changed={}", dist.display());
    if !dist.join("index.html").is_file() {
        panic!("embed-ui: {} has no index.html — run `npm run build` first", dist.display());
    }
    let mut files = Vec::new();
    let mut stack = vec![dist.clone()];
    while let Some(dir) = stack.pop() {
        for e in std::fs::read_dir(&dir).unwrap() {
            let p = e.unwrap().path();
            if p.is_dir() {
                stack.push(p);
            } else if p.is_file() {
                let rel = p.strip_prefix(&dist).unwrap().to_string_lossy().replace('\\', "/");
                files.push((rel, p.canonicalize().unwrap()));
            }
        }
    }
    files.sort();
    let mut out = String::from("/// Generated by build.rs from dist/ (feature embed-ui). Sorted by path.\npub static FILES: &[(&str, &[u8])] = &[\n");
    for (rel, abs) in &files {
        out.push_str(&format!("    ({rel:?}, include_bytes!({:?})),\n", abs.to_string_lossy()));
    }
    out.push_str("];\n");
    let dest = std::path::PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("ui_embed.rs");
    std::fs::write(dest, out).unwrap();
}
